services:
  - type: web
    name: artify-python-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend-python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false